# Generated by Django 4.2 on 2023-05-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
